Algoritmo "Exercício 1"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Escreva um algoritmo que mostre a tabuada de um número até 10
// Autor(a)    : Paloma Costa
// Data atual  : 11/04/2023
Var
i,r: inteiro


Inicio


para i de 1 ate 10 faca
      r <- (i * 1)
   escreval(" 1 x ", i, " = ", r)
fimpara

fimalgoritmo
