Algoritmo "Números de 1 a 10 (com enquanto...faca"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/04/2023
Var
j: inteiro


Inicio
j <- 1

enquanto j <= 10 faca
  escreval(j)
  j <- j + 1
fimenquanto


Fimalgoritmo